"""add_department_id_to_employees

Revision ID: ea9529594bad
Revises: d54b66d07023
Create Date: 2025-11-28 21:46:26.484156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea9529594bad'
down_revision: Union[str, None] = 'd54b66d07023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'department_id')
    # ### end Alembic commands ###
